### PR TITLE
Miscellaneous Changes

### PR DESCRIPTION
**Pull request by zoidbergwill**
- Fixed the `!help` command.
- We might wanna make docstring match the commands instead of the other way around, which is what I did
- Unless I'm missing something and `select_team` and `pop_teams` were different commands?
- We should throttle status announcements, but I think it's okay for now.
- I haven't tested the announcing of the game yet.

### CODE REVIEW

**Comment by veryhappythings** [comment]
Oh wow, thank you for this! I don't have time to merge it right this second but I will look into it ASAP. It's so nice when you get random PRs :)

**Comment by garykrige** [comment]
:+1:

**Comment by veryhappythings** [comment]
Right, back at my desk :) Again, thank you for this!

I'm pondering re-architecting how announcements are done across the board. In my last iteration of a bot like this, the organiser would ping the bot with an event when it wanted to do something, but then you have events going everywhere and it becomes rather hard to reason about and test, so I'm trying to make the organiser really dumb and not dependant on IO while the bot does all the announcing. I think this is the right way to do it, and your PR lines up with that, so yes, thanks!

**Comment by zoidbergwill** [comment]
Awesome, thanks for merging.

**Comment by zoidbergwill** [comment]
So I'm using this bot for an Overwatch PUG bot and I've made some issues on [my fork](https://github.com/zoidbergwill/discord-gather/issues) to track stuff that might not belong upstream, unless you have an interest in helping make this easily extendable for any game-specific stuff?

I think that'd be awesome.

The only difference so far is that team size, which I wanna move to an optional key in the config file.

But people have asked for tracking `Battle.net` IDs, and maybe tracking Steam IDs or URLs would be a useful upstream feature?

**Comment by veryhappythings** [comment]
I'm totally up for that - not quite sure how it'd work but what a cool idea. I'll take a look at your fork and see what we can do :)

**Pull request merged**
