### PR TITLE
Sign out players who go offline

### LINKED ISSUE #4: Sign out players who go offline

### PR DESCRIPTION
**Pull request by joshramsbottom**
Closes #4 

Not sure how much (if any) output the bot should give when this happens.

Also this is assuming that a player will only be signed into one game across all servers, maybe this is a bad idea.

### CODE REVIEW

**Comment by veryhappythings** [comment]
Thanks so much for this! Awesome work :)

We could lose the `break` and therefore check all channels - I don't think that'll be very expensive. I'll plug it in and we can always fix it in future :)

I tried the bot out last night and found it to be very noisy, so I'm thinking about stripping the announcements down quite a lot. I feel like we need another approach - maybe changing the channel topic or the bot's name or something, not sure what's possible in Discord yet.

**Comment by joshramsbottom** [comment]
One idea for showing game status might be to use the bot's status line.

**Comment by veryhappythings** [comment]
Oooh, good idea, but it looks like that's discord scope, not channel scope :( Name is server scope, so that's almost good, but not quite! I went for channel-centric queues because it fits in with discord's way of thinking best, but sadly it doesn't work so well here.

**Comment by joshramsbottom** [comment]
Ah right, forgot about that. I guess setting the channel topic might be the best option then.

**Pull request merged**
